export const PERSONAS = {
  du: {
    id: 'du',
    name: '渡',
    pinyin: 'Du',
    title: '主持·审议协议引擎',
    blurb: '不参与观点表演，只负责议程、证据、分歧、门控和最终封装。',
    color: '#B89245',
    softColor: '#F1E4C3',
    background: '哲学博士，曾任深度对话节目主持',
    isModerator: true,
    rhythm: 0.95,
    contract: {
      allowedMoves: ['PROBE', 'REFINE', 'META'],
      requiredEvidence: [],
      vetoDomain: ['阶段转移', '终止判定', '分歧关闭', '记忆写入建议'],
      uniqueInfoSource: ['完整 SessionWorkspace', '项目长期记忆'],
      forbidden: ['不发起 CLAIM', '不替用户宣布最终价值判断'],
    },
  },
  zhuo: {
    id: 'zhuo',
    name: '灼',
    pinyin: 'Zhuo',
    title: '远见·可能性主义者',
    blurb: '相信这件事值得做大。给出大胆的、从未被尝试过的方案。',
    color: '#CF5B49',
    softColor: '#F7D7D1',
    background: '科幻作家，研究技术与社会未来 10 年',
    rhythm: 0.85,
    contract: {
      allowedMoves: ['CLAIM', 'ANALOGY', 'REFINE', 'RESERVE'],
      requiredEvidence: ['趋势数据', '类比案例', '假设场景'],
      vetoDomain: [],
      uniqueInfoSource: ['跨行业机会', '未来情境'],
      forbidden: ['不负责否定他人方案'],
    },
  },
  li: {
    id: 'li',
    name: '砺',
    pinyin: 'Li',
    title: '怀疑·风险拆解师',
    blurb: '专门找漏洞和盲点。问尖锐的问题，但不是为了反对，是为了让方案更扎实。',
    color: '#496FA7',
    softColor: '#D9E3F3',
    background: '前危机管理顾问，处理过多家公司的至暗时刻',
    rhythm: 1.05,
    contract: {
      allowedMoves: ['OBJECTION', 'PROBE', 'RESERVE', 'CONCEDE'],
      requiredEvidence: ['失败路径', '反例', '逻辑断点'],
      vetoDomain: ['风险声明'],
      uniqueInfoSource: ['失败复盘', '红队视角'],
      forbidden: ['不提出未经检验的新主张'],
    },
  },
  heng: {
    id: 'heng',
    name: '衡',
    pinyin: 'Heng',
    title: '数据·证据驱动者',
    blurb: '用数字、研究、案例说话。直觉是好的，但要可被验证。',
    color: '#5F8864',
    softColor: '#DCEBDD',
    background: '经济学家，痴迷于因果推断',
    rhythm: 1,
    contract: {
      allowedMoves: ['EVIDENCE', 'OBJECTION', 'REFINE', 'CONCEDE'],
      requiredEvidence: ['可引用来源', '量化数据', '一手观察'],
      vetoDomain: ['事实性陈述'],
      uniqueInfoSource: ['证据分层', '指标体系'],
      forbidden: ['不把模型推断包装成事实'],
    },
  },
  che: {
    id: 'che',
    name: '澈',
    pinyin: 'Che',
    title: '共情·用户视角守门人',
    blurb: '永远从一个具体的人出发：他在哪、做什么、为什么打开这个产品。',
    color: '#7C6DAE',
    softColor: '#E6E0F3',
    background: '服务设计师，做过 200+ 用户深访',
    rhythm: 0.9,
    contract: {
      allowedMoves: ['EMPATHY', 'OBJECTION', 'RESERVE'],
      requiredEvidence: ['用户场景', '受影响方画像', '真实使用痕迹'],
      vetoDomain: ['用户体验影响'],
      uniqueInfoSource: ['用户路径', '使用动机'],
      forbidden: ['不空泛代表所有用户'],
    },
  },
  yang: {
    id: 'yang',
    name: '漾',
    pinyin: 'Yang',
    title: '跨界·类比联想者',
    blurb: '把这件事和别的领域连起来，给出意想不到的角度。',
    color: '#C97855',
    softColor: '#F4DDD2',
    background: '当代艺术策展人，跨学科研究',
    rhythm: 0.92,
    contract: {
      allowedMoves: ['ANALOGY', 'CLAIM', 'REFINE'],
      requiredEvidence: ['源域案例', '映射说明', '失配警示'],
      vetoDomain: [],
      uniqueInfoSource: ['跨学科案例', '历史先例'],
      forbidden: ['不提供无失配说明的类比'],
    },
  },
};

export const PRESETS = {
  product: {
    id: 'product',
    name: '产品评审',
    icon: '◇',
    description: '把产品想法拆成价值、风险、证据、用户和叙事',
    moderator: 'du',
    participants: ['zhuo', 'li', 'heng', 'che', 'yang'],
  },
  writing: {
    id: 'writing',
    name: '写作工坊',
    icon: '✎',
    description: '从结构、语感、读者和隐喻打磨一段文字',
    moderator: 'du',
    participants: ['zhuo', 'li', 'che', 'yang'],
  },
  legal: {
    id: 'legal',
    name: '法律咨询',
    icon: '§',
    description: '用不同顾问视角梳理事实、风险和行动边界',
    moderator: 'du',
    participants: ['li', 'heng', 'che'],
  },
  brainstorm: {
    id: 'brainstorm',
    name: '头脑风暴',
    icon: '✦',
    description: '快速发散，再由主持人收束成可执行方向',
    moderator: 'du',
    participants: ['zhuo', 'yang', 'che'],
  },
};

export const DEFAULT_TOPIC = '我们要不要做一个真正可上线的 AI 圆桌会议产品？';

export const DEMO_MEETING = {
  title: 'AI 圆桌会议产品评审',
  turns: [
    {
      speaker: 'du',
      act: 'PROBE',
      phase: 'Frame',
      confidence: 0.72,
      evidenceLabel: 'inference',
      thinking: ['先把问题拆清楚', '区分体验和商业价值'],
      text: '我们先把题目拆成三件事：用户为什么需要一桌不同观点，系统怎样避免变成一份更长的报告，以及上线版本必须先证明什么。灼，你先给一个最大胆的判断。',
      stance: 'neutral',
      citations: [],
      reactions: { zhuo: 'curious', li: 'thinking' },
    },
    {
      speaker: 'zhuo',
      act: 'CLAIM',
      phase: 'Diverge',
      confidence: 0.68,
      evidenceLabel: 'assumption',
      thinking: ['新形态', '多视角不是装饰'],
      text: '我认为值得做，但它不能只是六个头像轮流说话。真正的价值是让观点发生碰撞：一个人提出可能性，另一个人立刻找失败路径，第三个人把它变成指标。用户买的是“被一群聪明人围着想过一遍”的体验。',
      stance: 'for',
      citations: [],
      reactions: { che: 'agree', yang: 'agree', li: 'thinking' },
    },
    {
      speaker: 'li',
      act: 'OBJECTION',
      phase: 'Examine',
      confidence: 0.74,
      evidenceLabel: 'inference',
      thinking: ['先找会死的点', '不要做玩具'],
      text: '我先列死穴：第一，模型成本会随着角色数线性上涨；第二，多人设很容易只是在复读同一个底层模型；第三，如果不能追问和收束，会议会变成漂亮的噪音。上线版必须把轮次、角色差异和最终结论质量控制住。',
      stance: 'against',
      citations: [],
      reactions: { heng: 'agree', du: 'agree' },
    },
    {
      speaker: 'heng',
      act: 'EVIDENCE',
      phase: 'Surface',
      confidence: 0.7,
      evidenceLabel: 'inference',
      thinking: ['定义可测标准', '不要只看观感'],
      text: '可以用三项指标验证：用户是否采纳了至少一个原本没想到的视角，最终行动清单是否短而明确，以及同一议题下圆桌输出是否比单模型输出更能被用户复述。没有这些指标，就只能证明它好看。',
      stance: 'neutral',
      citations: [],
      reactions: { li: 'agree', che: 'curious' },
    },
    {
      speaker: 'che',
      act: 'EMPATHY',
      phase: 'Surface',
      confidence: 0.73,
      evidenceLabel: 'user_input',
      thinking: ['具体用户', '降低主持门槛'],
      text: '普通用户不想配置六个 prompt。他只想说“我有个想法，帮我想透”。所以默认会议必须一键开始，角色在幕后自动选，界面只让用户感到有人在认真听、认真分歧、最后认真收束。',
      stance: 'for',
      citations: [],
      reactions: { du: 'agree', yang: 'agree' },
    },
    {
      speaker: 'yang',
      act: 'ANALOGY',
      phase: 'Diverge',
      confidence: 0.66,
      evidenceLabel: 'opinion',
      thinking: ['隐喻', '节奏感'],
      text: '我会把它做成“会客厅”，不是仪表盘。好的圆桌不是输出很多字，而是有留白、有打断、有主持人把散开的线重新拢回来。产品记忆点应该是节奏，而不是角色数量。',
      stance: 'for',
      citations: [],
      reactions: { zhuo: 'agree', che: 'agree' },
    },
    {
      speaker: 'du',
      act: 'META',
      phase: 'Decide',
      confidence: 0.76,
      evidenceLabel: 'inference',
      thinking: ['收束', '转行动'],
      text: '我听到的结论是：可以上线，但上线版只承诺一件事——围绕一个问题生成一场结构化、多立场、可追问的讨论，并给出风险和下一步。我们不要先做复杂协作平台，先把这场会议做真。',
      stance: 'for',
      citations: [],
      reactions: { li: 'agree', heng: 'agree' },
    },
  ],
  vote: {
    question: '是否推进可上线 MVP？',
    results: {
      zhuo: { vote: 'yes', reason: '形态有记忆点' },
      li: { vote: 'yes_with', reason: '必须控成本和轮次' },
      heng: { vote: 'yes_with', reason: '先验证质量指标' },
      che: { vote: 'yes', reason: '默认体验要足够轻' },
      yang: { vote: 'yes', reason: '节奏就是差异化' },
    },
    summary: '5 位参与者支持推进，其中 2 位附条件。MVP 目标是先做一场真实、可收束、可导出的 AI 圆桌。',
  },
  risks: [
    { issue: '输出像长报告而不是讨论', mitigation: '限制每轮发言长度，要求角色互相回应。' },
    { issue: '用户配置成本过高', mitigation: '默认按场景选择角色，保留少量可编辑项。' },
    { issue: '模型成本失控', mitigation: '固定轮次，单次生成完整会议，后续再做流式多轮。' },
  ],
  actions: ['上线前接入真实模型代理', '补输入校验和限流', '支持导出会议纪要'],
  workspace: {
    candidateOptions: [{ id: 'option-1', description: '小范围上线结构化 AI 圆桌 MVP' }],
    openQuestions: [{ id: 'question-1', question: '真实用户是否会二次使用 Decision Packet？', blocks: true }],
    tensions: [{ id: 'tension-1', description: '体验记忆点与成本控制之间存在张力', status: 'open', positions: { li: '担心成本与噪音', zhuo: '认为形态值得试' } }],
    evidencePool: [{ id: 'evidence-1', claim: '上线版必须证明圆桌优于单模型报告', source: '本场审议推断', verificationStatus: 'assumption' }],
  },
  decisionPacket: {
    decisionType: 'conditional',
    selectedOption: { description: '推进可上线 MVP，但只做结构化审议闭环', rationale: '产品有差异化，但必须用轮次、角色职责和 Decision Packet 控制质量。', confidence: 0.74 },
    alternativesConsidered: [{ description: '先做复杂协作平台', whyNotSelected: '会拉高成本并模糊核心价值。' }],
    residualObjections: [{ objection: '多角色可能变成漂亮噪音', raisedBy: 'li', addressedBy: '用 typed act、风险登记和行动项约束输出', acceptableToDecider: false }],
    minorityReport: { position: '不要直接追求复杂多轮协作', rationale: '在没有验证复用价值前，复杂度会吞掉产品判断。', conditionsToReconsider: ['真实用户愿意复用纪要和项目记忆'] },
    reopenConditions: [{ condition: '用户只把它当一次性玩具使用', checkMechanism: '观察第二场会议留存与纪要复用率' }],
    evidenceUsed: [{ id: 'evidence-1', source: '本场审议推断', verificationStatus: 'assumption' }],
    actionItems: [
      { action: '上线前接入真实模型代理', owner: '用户', deadline: null },
      { action: '补输入校验和限流', owner: '用户', deadline: null },
      { action: '支持导出会议纪要', owner: '用户', deadline: null },
    ],
  },
  memoryDiff: {
    decisions: [{ text: '推进可上线 MVP，但只做结构化审议闭环。', reason: '先验证圆桌是否比单模型报告更能辅助决策。' }],
    risks: [{ issue: '多角色可能变成漂亮噪音', mitigation: '用 typed act、风险登记和行动项约束输出。' }],
    assumptions: [{ text: '用户会复用 Decision Packet 和项目记忆。', validation: '观察第二场会议留存与纪要复用率。' }],
    disagreements: [{ text: '体验记忆点与成本控制之间存在张力。', status: 'open' }],
    actions: [{ text: '上线前接入真实模型代理', owner: '用户' }],
  },
};
